package main

var targets = []string{
	"https://lenta.ru",
	"https://www.gazprom.ru",
	"https://lukoil.ru",
	"https://magnit.ru",
	"https://www.eurosib.ru",
	"https://www.vtb.ru",
	"https://www.gazprombank.ru",
	"https://www.gosuslugi.ru",
	"https://www.mos.ru/uslugi",
	"http://kremlin.ru",
	"http://government.ru",
	"https://www.nalog.gov.ru",
	"https://customs.gov.ru",
	"https://pfr.gov.ru",
	"https://rkn.gov.ru",
	"https://cloud.rkn.gov.ru/",
	"https://www.rbc.ru/",
	"https://www.rt.com/",
	"http://kremlin.ru/",
	"http://en.kremlin.ru/",
	"https://smotrim.ru/",
	"https://tass.ru/",
	"https://tvzvezda.ru/",
	"https://vsoloviev.ru/",
	"https://www.1tv.ru/",
	"https://www.vesti.ru/",
	"https://online.sberbank.ru/",
	"https://sberbank.ru/",
	"https://zakupki.gov.ru/",
}